CREATE TABLE articles (
  id        SERIAL PRIMARY KEY,
  title     TEXT NOT NULL,
  author    TEXT NOT NULL,
  body      TEXT NOT NULL,
  published DATE NOT NULL DEFAULT CURRENT_DATE
);

INSERT INTO articles (title, author, body, published) VALUES
  ('YugabyteDB scales distributed SQL to millions of transactions',
   'Priya Sharma',
   'YugabyteDB brings distributed SQL to modern cloud applications. It supports horizontal scaling while maintaining full ACID transactions. Teams migrating from PostgreSQL find near-zero application changes needed.',
   '2024-01-15'),
  ('How vector databases are reshaping AI applications',
   'Alex Chen',
   'Vector databases store and query high-dimensional embeddings for machine learning. Semantic search, recommendation engines, and retrieval-augmented generation all rely on efficient nearest neighbor search.',
   '2024-02-03'),
  ('Building resilient microservices with distributed transactions',
   'Maria Rodriguez',
   'Microservices architectures introduce distributed transaction complexity. Sagas and two-phase commit are common patterns. ACID guarantees at the database layer simplify consistency management.',
   '2024-02-18'),
  ('Row Level Security patterns for multi-tenant SaaS applications',
   'Sarah Kim',
   'Row level security enforces tenant isolation at the database layer without any application code changes. Multi-tenant SaaS platforms adopt this pattern for compliance and data governance.',
   '2024-03-20'),
  ('Change data capture for real-time event streaming pipelines',
   'Emma Thompson',
   'CDC captures row-level changes from database transaction logs. Kafka connectors stream changes to downstream consumers. Event sourcing and CQRS patterns benefit from low-latency replication.',
   '2024-04-22'),
  ('Indexing strategies for high-throughput OLTP workloads',
   'David Park',
   'Covering indexes eliminate heap fetches for frequently-run queries. Partial indexes reduce index size for sparse columns. Understanding query plans is essential for database performance tuning.',
   '2024-04-05'),
  ('Geo-distributed databases for global SaaS platforms',
   'Carlos Mendez',
   'Geo-distributed deployments place data near users to reduce read latency. Follower reads serve local traffic without hitting the primary. Writes route through a single region with synchronous replication.',
   '2024-05-10'),
  ('pgcrypto and column-level encryption for compliance',
   'Aisha Patel',
   'Column-level encryption protects sensitive PII without full database encryption overhead. pgcrypto provides symmetric and asymmetric functions. Key rotation is the hardest operational challenge.',
   '2024-05-28'),
  ('Operational observability: metrics, logs, and distributed traces',
   'Lars Eriksson',
   'Database observability combines latency metrics, slow query logs, and distributed traces. pg_stat_statements tracks cumulative query performance. Alert on SLO breaches to reduce mean time to recovery.',
   '2024-06-12'),
  ('Point-in-time recovery and time travel for forensic audits',
   'Jenna Walsh',
   'PITR restores a database to any past moment without a full backup restore. Combined with yb_read_time time travel queries, it covers both recovery and compliance audit scenarios at scale.',
   '2024-06-30');
