image:
  file: .ybdb.Dockerfile
tasks:
  - name: ybdb
    env:
      DATA_PATH: ybdb
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/${DATA_PATH}
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/${DATA_PATH} --advertise_address=$HOST --cloud_location=ybcloud.pandora.az1 --background=true

  - name: init-services
    env:
      ART_PATH: init-voyager-postgres
    init: |
      docker compose -f ${ART_PATH}/compose.yml pull
    command: |
      docker compose -f ${ART_PATH}/compose.yml up

  - name: psqlsh
    env:
      PGUSER: postgres
      PGPASSWORD: yugabyte
      PGHOST: 127.0.0.1
    init: |
      sudo apt-get update
      sudo apt-get install -y postgresql-contrib
    command: |
      gp ports await 5432
      psql -h $PGHOST -U $PGUSER -d postgres

  - name: yb-voyager
    env:
      DATA_PATH: voyager-data
      SCHEMA: public
      SRC_DB_TYPE: postgresql
      SRC_DB_ID: 'Chinook'
      SRC_USER: postgres
      SOURCE_DB_SCHEMA: public
      SRC_SECRET: 'yugabyte'
      TARGET_DB_ID: yugabyte
      TARGET_USER: yugabyte
      TARGET_SECRET: yugabyte
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/${DATA_PATH}
      wget -O ./yb-voyager https://raw.githubusercontent.com/yugabyte/yb-voyager/main/docker/yb-voyager-docker && chmod +x ./yb-voyager && sudo mv yb-voyager /usr/local/bin/yb-voyager
      gp ports await 5432

vscode:
  extensions:
    - ms-azuretools.vscode-docker

# exposed ports
ports:
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 15433
    name: yugabyted-ui
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
  - port: 5432
    name: psql
    onOpen: ignore
