services:
  postgresql:
    container_name: postgres
    image: postgres:14
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: yugabyte
      POSTGRES_DATABASE: postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
  voyager:
    container_name: yb-voyager
    image: yugabytedb/yb-voyager:latest
    command: "echo Hello from yb-voyager!"
volumes:
  postgresql_data: