#!/usr/bin/env python3
"""
Generate .devcontainer/<exercise>/devcontainer.json from:
  .devcontainer/base.json                 shared defaults (ports, build, extensions, …)
  .devcontainer/<exercise>/override.json  per-exercise unique config

Usage:
  python3 gen-devcontainers.py [exercise-dir …]

  With no arguments, processes every init-* directory that has an override.json.

Generator-only keys in override.json (stripped before writing devcontainer.json):
  extensions           list   replace base extensions entirely when present
  extraForwardPorts    list   appended to base forwardPorts
  extraPortsAttributes dict   merged into base portsAttributes
  extraExclude         list   extra paths added to files.exclude beyond the default set

Standard devcontainer keys whose presence in override.json triggers special handling:
  containerEnv         dict   deep-merged with base (additive)
  portsAttributes      dict   replaces base portsAttributes entirely when present
  runArgs              list   replaces base runArgs when present
  hostRequirements     dict   replaces base hostRequirements when present
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DC_DIR = os.path.dirname(SCRIPT_DIR)
ROOT_DIR = os.path.dirname(DC_DIR)


def load(path):
    with open(path) as f:
        return json.load(f)


def all_exercises():
    """List init-* dirs from the repo root — these are the workspace-root paths
    used in files.exclude and also match the .devcontainer/init-* structure."""
    return sorted(
        d for d in os.listdir(ROOT_DIR)
        if d.startswith("init-") and os.path.isdir(os.path.join(ROOT_DIR, d))
    )


def build_files_exclude(current, exercises, extra):
    """Always-hidden paths + every exercise directory except the current one."""
    out = {}
    for p in ["ybdb", "voyager-data", ".devcontainer", ".github"]:
        out[p] = True
    for ex in exercises:
        if ex != current:
            out[ex] = True
    for p in extra:
        out[p] = True
    return out


def generate(exercise, base, exercises):
    override_path = os.path.join(DC_DIR, exercise, "override.json")
    if not os.path.exists(override_path):
        return False

    ov = load(override_path)

    # validate required keys upfront for a clear error message
    for key in ("name", "postStartCommand"):
        if key not in ov:
            sys.exit(f"  ✗  {exercise}/override.json: missing required key '{key}'")

    # ── strip generator-only keys ─────────────────────────────────────────────
    extra_ports   = ov.pop("extraForwardPorts", [])
    extra_attrs   = ov.pop("extraPortsAttributes", {})
    extra_exclude = ov.pop("extraExclude", [])
    ext_override  = ov.pop("extensions", None)
    ports_replace = ov.pop("portsAttributes", None)   # full replacement if present

    out = {}

    # ── fixed key order matches existing devcontainer.json style ──────────────
    out["name"]  = ov.pop("name")
    out["build"] = base["build"]

    # optional passthrough keys — present in override only when needed
    for k in ("initializeCommand", "features", "mounts", "postCreateCommand", "waitFor",
              "postStopCommand"):
        if k in ov:
            out[k] = ov.pop(k)

    out["runArgs"]          = ov.pop("runArgs", base["runArgs"])
    out["containerEnv"]     = {**base["containerEnv"], **ov.pop("containerEnv", {})}
    out["hostRequirements"] = ov.pop("hostRequirements", base["hostRequirements"])

    out["postStartCommand"] = ov.pop("postStartCommand")

    extensions = (ext_override if ext_override is not None
                  else list(base["customizations"]["vscode"]["extensions"]))
    out["customizations"] = {
        "vscode": {
            "settings": {
                "task.allowAutomaticTasks": "on",
                "files.exclude": build_files_exclude(exercise, exercises, extra_exclude),
            },
            "extensions": extensions,
            "tasks": [],
        }
    }

    out["forwardPorts"] = list(dict.fromkeys(base["forwardPorts"] + extra_ports))

    attrs = {**(ports_replace if ports_replace is not None else base["portsAttributes"]),
             **extra_attrs}
    out["portsAttributes"] = attrs
    if "otherPortsAttributes" in ov:
        out["otherPortsAttributes"] = ov.pop("otherPortsAttributes")

    out["remoteUser"] = base["remoteUser"]

    if ov:
        print(f"  ⚠  {exercise}: unrecognised override keys: {list(ov.keys())}")

    out_path = os.path.join(DC_DIR, exercise, "devcontainer.json")
    with open(out_path, "w") as f:
        f.write("// Generated by gen-devcontainers.py — edit override.json instead.\n")
        json.dump(out, f, indent=2)
        f.write("\n")
    return True


def main():
    base      = load(os.path.join(DC_DIR, "base.json"))
    exercises = all_exercises()
    targets   = sys.argv[1:] if len(sys.argv) > 1 else exercises

    ok = skip = 0
    for ex in targets:
        if generate(ex, base, exercises):
            print(f"  ✓  {ex}/devcontainer.json")
            ok += 1
        else:
            print(f"  –  {ex}  (no override.json)")
            skip += 1
    print(f"\n{ok} generated, {skip} skipped.")


if __name__ == "__main__":
    main()
