version: '3.9'

services:
  mysql:
    image: mariadb:10.4
    restart: always
    network_mode: host
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --skip-grant-tables
    environment:
      MYSQL_ROOT_PASSWORD: 'yugabyte'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  voyager:
    image: yugabytedb/yb-voyager:latest
    command: "echo Hello from yb-voyager!"
volumes:
  mysql-data: