# Dependabot version-tracking stub — keep these in sync with DEBEZIUM_VERSION in
# .devcontainer/init-cdc-ybdb-pg/override.json
FROM quay.io/debezium/zookeeper:3.1.3.Final AS zookeeper
FROM quay.io/debezium/kafka:3.1.3.Final AS kafka
FROM quay.io/debezium/connect:3.5.2.Final AS connect
